config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :stores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :store

  validates :value_contact, presence: true
  validates :type_contact, presence: true, uniqueness: true
end

app/models/manager.rb
class Manager < ApplicationRecord

  belongs_to :store
  validates :name, presence: true
  validates :birthdate, presence: true
  
end

app/models/store.rb
class Store < ApplicationRecord

  has_one :manager, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  
  accepts_nested_attributes_for :manager

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :set_store, only: %i[ new edit]
  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|      
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        set_lojas
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        set_lojas
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_store
      @stores = Store.all
    end


    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:type_contact, :value_contact, :store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.includes(:manager).all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
    @store.build_manager
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_path, status: :see_other, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, manager_attributes:[:name, :birthdate])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Type contact:</strong>
    <%= contact.type_contact %>
  </p>

  <p>
    <strong>Value contact:</strong>
    <%= contact.value_contact %>
  </p>

  <p>
    <strong>Store:</strong>
    <%= contact.store_id %>
  </p>

</div>

app/views/contacts/_form.html.erb
<h1>Novo Contato</h1>

<%= form_with(model: [@store, @contact], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :type_contact %>
    <%= form.text_field :type_contact, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :value_contact %>
    <%= form.text_field :value_contact, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :store_id %>
    <%= form.collection_select :store_id,@stores,:id,:name, prompt: "Selecione uma loja",class: 'form-control'  %>
  </div>


  <div class="form-group">
    <%= form.submit 'Criar Contato', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contacts" %>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shopping Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
<% if store.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

    <ul>
        <% store.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>

    <h2> Dados do Gerente</h2>
    <!-- Campo para Nome do Gerente -->
    <%= form.fields_for :manager do |manager_form| %>
      <%= manager_form.label :name, "Nome do Gerente", style: "display: block" %>
      <%= manager_form.text_field :name %>
    
      <%= manager_form.label :birthdate, "Data de nascimento", style: "display: block" %>
      <%= manager_form.date_field :birthdate %>
    
    <% end %>
    
    <div>
        <%= form.submit %>
    </div>
    <% end %>

app/views/stores/_store.html.erb
<!-- app/views/lojas/show.html.erb -->

<h1> Loja <%= @store.name %>

<p><strong>Gerente:</strong> <%= @store.manager&.name %></p>

<h2>Contatos</h2>
<ul> 
  
  <% @store.contacts.each do |contact|%>
  <li> 
  <strong> <%= contact.type_contact %>: </strong>
  <p><%= contact.value_contact%> </p>
  </li>
  <% end %>
</ul>

<%= link_to 'Voltar', stores_path, class: 'btn btn-secondary' %>

app/views/stores/edit.html.erb
<% content_for :title, "Editing store" %>

<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<!-- app/views/lojas/index.html.erb -->
<h1>Lojas</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome da Loja</th>
      <th>Nome do Gerente</th>
      <th>Detalhes</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.id %></td>
        <td><%= store.name %></td>
        <td><%= store.manager&.name %></td>
        <td><%= link_to 'Detalhes', store_path(store), class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nova Loja', new_store_path, class: 'btn btn-success' %>

app/views/stores/new.html.erb
<% content_for :title, "New store" %>

<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>